FROM node:10

WORKDIR /usr/src/app

RUN git clone https://github.com/angus151/openfisca_nsw_form_generator.git 
RUN cd openfisca_nsw_form_generator/form-generator/ && npm i --no-fund

EXPOSE 4200

CMD npm start --prefix openfisca_nsw_form_generator/form-generator/
